### ISSUE TITLE
Transitioning states based on events?

### ISSUE THREAD

**Issue by myndzi** [nickfargo/state#20]
Say I have something like a Paint clone, and I am in the main state with the selection tool. If I click (mousedown -> mouseup), nothing happens; if I click and drag (mousedown -> mousemove), I change to a 'selecting' state. Is there an easy way to implement this kind of behavior? It seemed like transitions were the answer, but I don't see an easy way to get a notification of mousemove/mouseup to make the determination about whether to proceed or not. What's the proper way to tie in some kind of external asynchronous notification to the state machine?

**Comment by nickfargo** [comment]
If your “machine” object’s state-space is fairly simple, one way to go might be to replicate the DOM events you need and `emit` them into your object, something like:

``` js
// Forwards the named DOM events of `$source` to a `state`ful `receiver`
function watch ( $source, receiver, eventTypes ) {
  var i, l, eventType;
  for ( i = 0, l = eventTypes.length; i < l; i++ ) {
    eventType = eventTypes[i];
    $source.on( eventType, ( function ( eventType ) {
      return function ( event ) {
        receiver.state().emit( eventType, [event] );
      };
    }( eventType ) ));
  }
}


// A `state`ful object that will `watch` for mouse input
var motionDetector = {};

state( motionDetector, 'abstract', {

  // `cold` state -- no mouse buttons pressed; movement does nothing
  cold: state( 'default initial', {
    events: {
      mousedown: function ( event ) {
        this.state('-> hot');
      }
    }
  }),

  // `hot` state -- button pressed; movement will trigger `dragging`
  hot: state({
    events: {
      mousemove: function ( event ) {
        this.state('-> dragging');
      },
      mouseup: function ( event ) {
        this.state('-> cold');
      }
    }
  }),

  // `dragging` state -- do stuff; return to `cold` when complete
  dragging: state({
    events: {
      mousemove: function ( event ) {
        // TODO: get coords from `event`, update a bounding rect or whatever
      },
      mouseup: function ( event ) {
        // TODO: react externally to the completed drag
        this.state('-> cold');
      }
    }
  })
});

watch( $(document), motionDetector, [
  'mousedown', 'mousemove', 'mouseup'
]);
```

Again, all you’re doing here is just `emit`ting the DOM events you catch and feeding them into your object (`motionDetector`). Those events are received by the object’s _current state_, whatever that happens to be at the time, such that each `State` will react to the event (on behalf of its owner `motionDetector`) in its own particular way.

**Comment by myndzi** [comment]
Right, but in that case I need extra events that basically act as holding pens while waiting for something, and I also have to pass some state around between 'hot' and other states, such as a reference to the marquee object. It seems like a transition expression would be good here, but it can't react to events directly. I wasn't sure if there's a better way to approach the problem, or if this is as good as it gets...?

In my mockup, I wound up having multiple 'holding' events (mouse down while selection exists, mouse down while selection doesn't exist), and was starting to feel like I should be combining the functionality somehow.

**Comment by nickfargo** [comment]
Probably me being obtuse, but I’m not quite clear on what you’re trying to solve — might help to throw in some example code of the attempts thus far …

Meantime I’ll take some stabs in the dark:

> I also have to pass some state around between 'hot' and other states, such as a reference to the marquee object.

You can pass arguments to `this.state` along with the “transition arrow” string, and these will be conveyed to a state’s transitional events (e.g. `enter`, `exit`):

``` js
mousemove: function ( event ) {
  var $marquee = $('#marquee');
  this.state( '-> dragging', event, $marquee );
}
// ...
dragging: state({
  events: {
    enter: function ( transition, argv ) {
      var event = argv[0], $marquee = argv[1];
    }
    // ...
  }
});
```

Likewise you can pass whatever arguments you want when `emit`ting your own state events:

``` js
function watch ( // ...
  // ...
      return function ( event ) {
        receiver.state().emit( eventType, [ jQueryEvent, myStuff = {
          whatever: 'arguments',
          you: 'want'
        }]);
      }
  // ...
}

state( motionDetector, // ...
  cold: state( // ...
    events: {
      mousedown: function ( jQueryEvent, myStuff ) {
        // ...
      }
    }
  }),
  // ...
});
```

It may help — and this generally scales better too — to avoid `emit`ting events for this case, and just define methods in your states to handle the DOM events. You call them just as if they were plain old methods on your “machine” object; so …

… `watch` becomes

``` js
function watch ( $source, receiver, eventTypes ) {
  var i, l, eventType;
  for ( i = 0, l = eventTypes.length; i < l; i++ ) {
    eventType = eventTypes[i];
    $source.on( eventType, ( function ( eventType ) {
      return function ( event ) {
        receiver[ 'on' + eventType ]( event ); // called as a method
      };
    }( eventType ) ));
  }
}
```

… and your state declaration becomes …

``` js
var motionDetector = {};

state( motionDetector, 'abstract', {

  // `cold` state -- no mouse buttons pressed; movement does nothing
  cold: state( 'default initial', {
    onmousedown: function ( event ) {
      this.state('-> hot');
    }
  }),

  // `hot` state -- button pressed; movement will trigger `dragging`
  hot: state({
    onmousemove: function ( event ) {
      this.state( '-> dragging', event );
    },
    onmouseup: function ( event ) {
      this.state('-> cold');
    }
  }),

  // `dragging` state -- do stuff; return to `cold` when complete
  dragging: state({
    enter: function ( transition, argv ) {
      var event = argv[0];
    },
    onmousemove: function ( event ) {
      // TODO: get coords from `event`, update a bounding rect or whatever
    },
    onmouseup: function ( event ) {
      // TODO: react externally to the completed drag
      this.state('-> cold');
    }
  })
});
```

But again, I’m not sure what if any part of this is shedding light on the question …

**Comment by myndzi** [comment]
I guess an easy way to phrase it would be, is there a way to do what you just wrote and use a transition instead of the 'hot' state? Or should that not be done?

'Hot' isn't really a state that's doing anything, and it becomes duplicated code if I write it that way, along with basically passing its inputs to its outputs, both of which make me think maybe there's a better way. I could be completely incorrect, of course.

**Comment by nickfargo** [comment]
Ah, I see.

My instinct is that, in this case, that should not be done, since here the `hot` state, while not appearing to be “doing” anything per se, _does_ act as the determining agent for whether the successive input should result in either transitioning on to `dragging` or falling back to `cold`.

A transition, on the other hand, generally should have its destination determined from the outset, and simply act as the “vehicle” for transporting the stateful object’s _currency_ from one specific point in “state-space-time” to another specific point …

… or to put it another way (sans physics-envy), a transition is a means for the object’s currency to travel from one specific state to another specific state, and to do so asynchronously if so ordered, in which case the transition will `arrive` at its destination during some future turn of the event loop.

---

As for how to avoid duplicating code, if I understand the question correctly, I think the object model used by `State` provides a lot of freedom here. Taking from the most recent example, one case could focus on the `onmouseup` method, which here (almost) shares common behavior between `hot` and `dragging`. Assuming the behavior were in fact identical, one possibility then is to `extend` each state from a common abstract parastate; e.g.:

``` js
state( motionDetector, // ...

  generallyTorrid: state( 'abstract', {
    onmouseup: function ( event ) {
      this.state('-> cold');
    }
  }),

  hot: state.extend( 'generallyTorrid', {
    onmousemove: function ( event ) {
      this.state( '-> dragging', event );
    }
    // inherits `onmouseup` from the parastate
  }),

  dragging: state.extend( 'generallyTorrid', {
    // ...
    onmousemove: function ( event ) {
      // TODO: get coords from `event`, update a bounding rect or whatever
    }
    // inherits `onmouseup` from the parastate
  })
});
```

You would choose less silly names for all of these states, of course, but that’s the gist of it.

Another option, if it makes more sense to do so, is to structure the states in the more classical single-inheritance pattern, as nested substates of a common superstate … there are many options for this, really, and the best way forward, I think, thus depends on how thoroughly the full scope of your object’s state space can be known and described.

**Comment by myndzi** [comment]
Okay, thanks for the clarification :) I think I will see where inheritance can get me and go from there.
