### ISSUE TITLE
State status and roadmap?

### ISSUE THREAD

**Issue by zoomclub** [nickfargo/state#9]
While looking for a FSM Javascript API I found State. It looks very comprehensive and well done. I'm hoping to look into it further but I'm wondering about the tests, it looks like there are a number of them not passing. What are your plans for State? Is it ready to be used by Javascript apps? If so I'd like to learn more...

Thom

**Comment by nickfargo** [comment]
The tests published at http://statejs.org/tests are a qunit suite for versions prior to 0.1.0, and this page needs to be updated to reflect the latest version of the package and its new mocha test suite.

Working tests for the current version (0.1.x) are located in the `test` directory, and can be run in node against mocha. For example:

``` bash
$ mocha --compilers coffee:coffee-script -R spec
```

In the coming days I plan to commit the project's binaries including the `bin/test` test runner script, and also publish the tests' html rendering to statejs.org.

Thanks for calling attention to this.

**Comment by zoomclub** [comment]
Thanks, this is good to know. In the next days I'm organizing my code around the FSM design. You have good descriptions of how State works but it gets a bit abstract without a demo. Any chance of having a demo that shows of the State features and options, maybe something graphic?

**Comment by nickfargo** [comment]
More diagrams and concrete examples in JavaScript will indeed be helpful for the documentation and are on the agenda.

In the meantime, [**will**](http://github.com/nickfargo/will) and [**might**](http://github.com/nickfargo/might) are a couple of young projects that are field-testing **state** and may be of some interest if the literate coffeescript is to your taste.

The **will** library is a Futures-Promises/A+ implementation that uses **state** to define and differentiate the behaviors of its main [`Deferral`](https://github.com/nickfargo/will/blob/master/src/deferral.coffee.md#states) prototype. In turn **might** defines a [`Potential`](https://github.com/nickfargo/might/blob/master/src/potential.coffee.md#states) prototype that extends `Deferral` with additional states and reference-counting behavior to account for cancellations of futures. Each case makes use of some common state attributes and inheritance patterns.

**Comment by nickfargo** [comment]
Issues raised here are to an extent addressed on gh-pages coincident with release of version 0.2:
- added diagrams with advanced depictions of object model
- some examples reworked, distilled; poorer examples eliminated
- tests now runnable via `bin/test` rather than published to gh-pages
  - may revisit this later by pretty-publishing the test files alongside the existing [source](http://statejs.org/source/) section, and adding a “Run” button to each file that feeds it through mocha in the browser

Closing for now, but if specific questions remain please do add them.

**Comment by zoomclub** [comment]
Like the new updates, its becoming clear, will read on...

**Comment by nickfargo** [comment]
Great! I’ll be interested to hear how it goes. Clarifying the docs and steamrolling that learning curve is a top priority.
